# Generated by Django 4.0.1 on 2022-05-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='polymorphic_ctype',
        ),
    ]
